---
- hosts: localhost
  gather_facts: false
  tasks:
    - gcp_compute_instance:
        name: "{{ machine_name }}"
        deletion_protection: no
        machine_type: "{{ machine_type }}"
        zone: "{{ zone }}"
        project: "{{ project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ service_file }}"
        status: TERMINATED
